- name: installing nginx
  hosts: all 
  become: yes
  vars:
    ansible_ssh_private_key_file: /path/to/chandra.pem
  tasks:
  - name: installing nginx
    ansible.builtin.yum:
      name: nginx
      state: installed

  - name: enable and star nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes