- name: DEMO is on ansible configuration
  hosts: centos
  become: yes
  tasks:
  - name: Install httpd package
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes