- name: DEMO is on ansible configuration
  hosts: ec2-user
  tasks:
  - name: install nginx  
    ansible.builtin.yum:
      name: nginx
      state: installed
  
  - name: service starting
    ansible.builtin.service:
      name: nginx
      state: started