- name: DEMO is on ansible configuration
  hosts: ec2-user
  tasks:
  - name: Update package cache
    package:
      name: '*'
      state: latest

  - name: Install Nginx
    package:
      name: nginx
      state: present

  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: yes